# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-21 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='voice',
            new_name='votes',
        ),
    ]
